CREATE TABLE Cities(
  Id INT PRIMARY KEY IDENTITY,
  [Name] VARCHAR(20) NOT NULL,
  CountryCode CHAR(2) NOT NULL
)

CREATE TABLE Hotels(
  Id INT PRIMARY KEY IDENTITY,
  [Name] VARCHAR(30) NOT NULL,
  CityId INT FOREIGN KEY REFERENCES Cities(Id) NOT NULL,
  EmployeeCount INT NOT NULL,
  BaseRate DECIMAL(15, 2)
)

CREATE TABLE Rooms(
  Id INT PRIMARY KEY IDENTITY,
  Price DECIMAL(15, 2) NOT NULL,
  [Type] VARCHAR(20) NOT NULL,
  Beds INT NOT NULL,
  HotelId INT FOREIGN KEY REFERENCES Hotels(Id) NOT NULL
)

CREATE TABLE Trips(
  Id INT PRIMARY KEY IDENTITY,
  RoomId INT FOREIGN KEY REFERENCES Rooms(Id) NOT NULL,
  BookDate DATETIME NOT NULL, CHECK (BookDate <= ArrivalDate),
  ArrivalDate DATETIME NOT NULL, CHECK (ArrivalDate <= ReturnDate),
  ReturnDate DATETIME NOT NULL,
  CancelDate DATETIME
)

CREATE TABLE Accounts(
  Id INT PRIMARY KEY IDENTITY,
  FirstName VARCHAR(50) NOT NULL,
  MiddleName VARCHAR(20),
  LastName VARCHAR(50) NOT NULL,
  CityId INT FOREIGN KEY REFERENCES Cities(Id) NOT NULL,
  BirthDate DATE NOT NULL,
  Email NVARCHAR(100) UNIQUE NOT NULL
)

CREATE TABLE AccountsTrips(
  AccountId INT FOREIGN KEY REFERENCES Accounts(Id) NOT NULL,
  TripId INT FOREIGN KEY REFERENCES Trips(Id) NOT NULL,
  Luggage INT NOT NULL, CHECK(Luggage >= 0),
  CONSTRAINT PK_AccountsTrips PRIMARY KEY (AccountId, TripId)
)

