CREATE TABLE Clients(
  ClientId INT PRIMARY KEY IDENTITY,
  FirstName VARCHAR(50) NOT NULL,
  LastName VARCHAR(50) NOT NULL,
  Phone CHAR(12) NOT NULL
)

CREATE TABLE Mechanics(
  MechanicId INT PRIMARY KEY IDENTITY,
  FirstName VARCHAR(50) NOT NULL,
  LastName VARCHAR(50) NOT NULL,
  [Address] VARCHAR(255) NOT NULL
)

CREATE TABLE Models(
  ModelId INT PRIMARY KEY IDENTITY,
  [Name] VARCHAR(50) NOT NULL UNIQUE
) 

CREATE TABLE Jobs(
  JobId INT PRIMARY KEY IDENTITY,
  ModelId INT FOREIGN KEY REFERENCES Models(ModelId),
  [Status] VARCHAR(11) NOT NULL CHECK ([Status] IN ('Pending', 'In Progress', 'Finished')) DEFAULT 'Pending',
  ClientId INT FOREIGN KEY REFERENCES Clients(ClientId),
  MechanicId INT FOREIGN KEY REFERENCES Mechanics(MechanicId),
  IssueDate DATETIME NOT NULL,
  FinishDate DATETIME 
)

CREATE TABLE Orders(
  OrderId INT PRIMARY KEY IDENTITY,
  JobId INT FOREIGN KEY REFERENCES Jobs(JobId),
  IssueDate DATETIME,
  Delivered BIT NOT NULL DEFAULT 'False'
)    

CREATE TABLE Vendors(
  VendorId INT PRIMARY KEY IDENTITY,
  [Name] VARCHAR(50) NOT NULL UNIQUE
)

CREATE TABLE Parts(
  PartId INT PRIMARY KEY IDENTITY,
  SerialNumber VARCHAR(50) NOT NULL UNIQUE,
  Description VARCHAR(255),
  Price DECIMAL(8, 2) NOT NULL CHECK (Price > 0),
  VendorId INT FOREIGN KEY REFERENCES Vendors(VendorId) NOT NULL,
  StockQty INT NOT NULL CHECK (StockQty >= 0) DEFAULT 0
)

CREATE TABLE OrderParts(
  OrderId INT FOREIGN KEY REFERENCES Orders(OrderId),
  PartId INT FOREIGN KEY REFERENCES Parts(PartId),
  Quantity INT NOT NULL CHECK(Quantity > 0) DEFAULT 1,
  CONSTRAINT PK_OrderPart PRIMARY KEY (OrderId, PartId)
)

CREATE TABLE PartsNeeded(
  JobId INT FOREIGN KEY REFERENCES Jobs(JobId),
  PartId INT FOREIGN KEY REFERENCES Parts(PartId),
  Quantity INT NOT NULL CHECK(Quantity > 0) DEFAULT 1,
  CONSTRAINT PK_PartNeeded PRIMARY KEY (JobId, PartId)
)



