CREATE TABLE Cities(
  CityID INT PRIMARY KEY NOT NULL,
  Name NVARCHAR(30) NOT NULL
)

CREATE TABLE Customers(
  CustomerID INT PRIMARY KEY NOT NULL,
  Name NVARCHAR(30) NOT NULL,
  Birthday DATE NOT NULL,
  CityID INT FOREIGN KEY REFERENCES Cities(CityID)
)

CREATE TABLE Orders(
  OrderID INT PRIMARY KEY NOT NULL,
  CustomerID INT FOREIGN KEY REFERENCES Customers(CustomerID)
)

CREATE TABLE OrderItems(
  OrderID INT NOT NULL,
  ItemID INT NOT NULL,
  CONSTRAINT PK_CompositeKey PRIMARY KEY (OrderID, ItemID),
  CONSTRAINT FK_OrderId FOREIGN KEY (OrderID)
  REFERENCES Orders(OrderID)
)
  
CREATE TABLE ItemTypes(
  ItemTypeID INT PRIMARY KEY NOT NULL,
  Name NVARCHAR(30) NOT NULL
)

CREATE TABLE Items(
  ItemID INT PRIMARY KEY NOT NULL,
  Name NVARCHAR(30) NOT NULL,
  ItemTypeID INT FOREIGN KEY REFERENCES ItemTypes(ItemTypeID)
)

ALTER TABLE OrderItems
ADD CONSTRAINT FK_ItemId FOREIGN KEY (ItemID)
REFERENCES Items(ItemID)